import { Injectable } from '@nestjs/common';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit');

export interface InvoicePdfData {
  invoiceNumber: string;
  amount: number;
  currency: string;
  dueDate: Date;
  status: string;
  notes?: string;
  client: {
    companyName: string;
    contactName?: string;
    email: string;
    phone?: string;
    address?: string;
  };
  brand: {
    name: string;
    logoUrl?: string;
    colors?: Record<string, string>;
  };
  sale: {
    description?: string;
  };
  createdAt: Date;
}

@Injectable()
export class InvoicePdfService {
  async generatePdf(data: InvoicePdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const primaryColor = data.brand.colors?.primary || '#1a1a2e';
      const accentColor = data.brand.colors?.accent || '#16213e';

      // Header
      doc.fontSize(24).fillColor(primaryColor).text(data.brand.name, 50, 50);
      doc.fontSize(10).fillColor('#666').text('INVOICE', 400, 50, { align: 'right' });
      doc.fontSize(18).fillColor(primaryColor).text(data.invoiceNumber, 400, 65, { align: 'right' });

      doc.moveTo(50, 100).lineTo(545, 100).strokeColor(accentColor).lineWidth(2).stroke();

      // Invoice details
      let y = 120;
      doc.fontSize(10).fillColor('#333');
      doc.text('Date:', 50, y);
      doc.text(data.createdAt.toLocaleDateString(), 120, y);
      y += 18;
      doc.text('Due Date:', 50, y);
      doc.text(data.dueDate.toLocaleDateString(), 120, y);
      y += 18;
      doc.text('Status:', 50, y);
      doc.fillColor(data.status === 'PAID' ? '#27ae60' : '#e74c3c').text(data.status, 120, y);
      doc.fillColor('#333');

      // Bill To
      y += 40;
      doc.fontSize(12).fillColor(primaryColor).text('Bill To:', 50, y);
      y += 20;
      doc.fontSize(10).fillColor('#333');
      doc.text(data.client.companyName, 50, y);
      y += 15;
      if (data.client.contactName) {
        doc.text(data.client.contactName, 50, y);
        y += 15;
      }
      doc.text(data.client.email, 50, y);
      y += 15;
      if (data.client.phone) {
        doc.text(data.client.phone, 50, y);
        y += 15;
      }
      if (data.client.address) {
        doc.text(data.client.address, 50, y);
        y += 15;
      }

      // Items table
      y += 30;
      doc.rect(50, y, 495, 25).fill(accentColor);
      doc.fontSize(10).fillColor('#fff');
      doc.text('Description', 60, y + 7);
      doc.text('Amount', 430, y + 7, { align: 'right' });

      y += 25;
      doc.fillColor('#333');
      const description = data.sale.description || 'Services rendered';
      doc.text(description, 60, y + 7);
      doc.text(`${data.currency} ${data.amount.toFixed(2)}`, 430, y + 7, { align: 'right' });

      y += 25;
      doc.moveTo(50, y).lineTo(545, y).strokeColor('#ddd').lineWidth(1).stroke();

      // Total
      y += 15;
      doc.fontSize(12).fillColor(primaryColor);
      doc.text('Total:', 350, y);
      doc.text(`${data.currency} ${data.amount.toFixed(2)}`, 430, y, { align: 'right' });

      // Notes
      if (data.notes) {
        y += 50;
        doc.fontSize(10).fillColor('#666');
        doc.text('Notes:', 50, y);
        y += 15;
        doc.text(data.notes, 50, y, { width: 495 });
      }

      // Footer
      doc.fontSize(8).fillColor('#999');
      doc.text(
        `Generated by ${data.brand.name} via Sentra Core`,
        50,
        doc.page.height - 50,
        { align: 'center', width: 495 },
      );

      doc.end();
    });
  }
}
