ALTER TYPE "LeadStatus" RENAME VALUE 'CLOSED_WON' TO 'WON';
ALTER TYPE "LeadStatus" RENAME VALUE 'CLOSED_LOST' TO 'LOST';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NCE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'INVALID';
