ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'SALE_CREATED';
ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'LEAD_CREATED';
ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'LEAD_ASSIGNED';
ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'LEAD_CONTRIBUTOR_ADDED';
ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'CLIENT_ASSIGNED';
ALTER TYPE "GlobalNotificationType" ADD VALUE IF NOT EXISTS 'CLIENT_PM_ASSIGNED';
